### ISSUE TITLE
`client.shutdown()` produces `KeyError` exception

### ISSUE THREAD

**Issue by ndim** [lack/soundcraft-utils#26]
This needs to be re-verified after the session-dbus merge, and this issue is to keep track of that check needing to be done.

Apparently, normal operation of `client.shutdown()` produces a `KeyError` exception with traceback:

```
$ python -c 'from soundcraft.dbus import Client; client = Client(); client.shutdown()'
New io.github.soundcraft_utils.notepad connected
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pydbus/subscription.py", line 52, in <lambda>
    callback = (lambda con, sender, object, iface, signal, params: signal_fired(sender, object, iface, signal, params.unpack())) if signal_fired is not None else lambda *args: None
  File "/usr/lib/python3.8/site-packages/pydbus/proxy_signal.py", line 15, in signal_fired
    callback(*params)
  File "/home/user/soundcraft-utils/soundcraft/dbus.py", line 322, in _onAdded
    proxyDevice = self.bus.get(BUSNAME, path)
  File "/usr/lib/python3.8/site-packages/pydbus/proxy.py", line 59, in get
    return CompositeInterface(introspection)(self, bus_name, object_path)
  File "/usr/lib/python3.8/site-packages/pydbus/proxy.py", line 118, in CompositeInterface
    raise KeyError("object does not export any interfaces; you might need to pass object path as the 2nd argument for get()")
KeyError: 'object does not export any interfaces; you might need to pass object path as the 2nd argument for get()'
io.github.soundcraft_utils.notepad service disconnected
```

This can be avoided by running the following code instead to shut down the service:

```python
bus = pydbus.SessionBus()
service = bus.get("io.github.soundcraft_utils.notepad")
service.Shutdown()
```

or as a one liner

```python
pydbus.SessionBus().get("io.github.soundcraft_utils.notepad").Shutdown()
```

However, what is the purpose of `client.shutdown()` then?

**Comment by ndim** [comment]
Not sure how this translates to socranop and what exact problems are still there, but at least the calls are

```python
import socranop.dbus
client = socranop.dbus.Client()
client.shutdown()
```

or

```python
import socranop.dbus
socranop.dbus.Client().shutdown()
```

versus

```python
import pydbus
pydbus.SessionBus().get("io.github.socratools.socranop").Shutdown()
```

**Comment by ndim** [comment]
Appears to be still the case. Re-filed against socranop at https://github.com/socratools/socranop/issues/20.
